apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-degraded.powerautomate: "true"
    notifications.argoproj.io/subscribe.on-sync-succeeded.powerautomate: "true"
  name: nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/djenkins-freedom-tech/nginx.git
    targetRevision: HEAD
    path: nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
