apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-broken
  labels:
    app: nginx-broken
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-broken
  template:
    metadata:
      labels:
        app: nginx-broken
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /non-existent-endpoint
              port: 80
            initialDelaySeconds: 1
            periodSeconds: 3
            failureThreshold: 1
