apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    notifications.argoproj.io/subscribe.on-degraded.webhook: powerautomate
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /non-existent
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 1
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m

